image:
  repository: gitea/gitea
  tag: "1.22.6"
  pullPolicy: IfNotPresent

service:
  httpPort: 3000
  httpNodePort: 30082
  sshPort: 22
  sshNodePort: 30022

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

ingress:
  enabled: true
  className: traefik
  host: git.local
