apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "resume-web.fullname" . }}-html
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
  labels:
    {{- include "resume-web.labels" . | nindent 4 }}
data:
  index.html: |
{{ .Files.Get "files/index.html" | indent 4 }}
