apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "resume-web.fullname" . }}-assets
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
  labels:
    {{- include "resume-web.labels" . | nindent 4 }}
data:
  bootstrap.min.css: |
{{ .Files.Get "files/bootstrap.min.css" | indent 4 }}
  bootstrap.bundle.min.js: |
{{ .Files.Get "files/bootstrap.bundle.min.js" | indent 4 }}
