apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: resume-web
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: http://gitea-http.gitea.svc:3000/jaehee/osc-k8s-resume.git
    targetRevision: main
    path: charts/resume-web
    helm:
      releaseName: resume-web
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: resume
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
  revisionHistoryLimit: 5
