apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  labels:
    app: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
        - name: gitea
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: USER_UID
              value: "1000"
            - name: USER_GID
              value: "1000"
            - name: GITEA__security__INSTALL_LOCK
              value: "true"
            - name: GITEA__server__ROOT_URL
              value: "http://192.168.56.21:30082/"
            - name: GITEA__server__HTTP_PORT
              value: "3000"
            - name: GITEA__server__DISABLE_SSH
              value: "false"
            - name: GITEA__server__SSH_PORT
              value: "{{ .Values.service.sshNodePort }}"
            - name: GITEA__database__DB_TYPE
              value: "sqlite3"
            - name: GITEA__database__PATH
              value: "/data/gitea/gitea.db"
            - name: GITEA__service__DISABLE_REGISTRATION
              value: "false"
            - name: GITEA__service__REQUIRE_SIGNIN_VIEW
              value: "false"
          ports:
            - name: http
              containerPort: {{ .Values.service.httpPort }}
            - name: ssh
              containerPort: {{ .Values.service.sshPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          emptyDir: {}
